plugins {
    id 'com.android.application'
}

android {
    namespace 'com.aaryanediting.app'
    compileSdk 36

    defaultConfig {
        applicationId 'com.aaryanediting.app'
        minSdk 24
        targetSdk 36
        versionCode 5
        versionName '5.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }

        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.core:core:1.16.0'
}
